---
- name: Install Java
  hosts: app_server
  become: yes
  become_user: root
  roles:
    - geerlingguy.java

- name: Download Application from Repo
  hosts: app_server
  tasks:
    - get_url:
        force: yes
        url: "{{ lookup('env','ARTIFACT_URL') }}"
        dest: "/tmp/{{ lookup('env','APP_NAME') }}.jar"
    - stat: 
        path: "/tmp/{{ lookup('env','APP_NAME') }}.jar"

- name: Setup Spring Boot
  hosts: app_server
  become: yes
  become_user: root
  roles: 
    - { role: pellepelster.springboot-role,
        spring_boot_file: "{{ lookup('env','APP_NAME') }}.jar",
        spring_boot_file_source: "/tmp/{{ lookup('env','APP_NAME') }}.jar",
        spring_boot_application_id: "{{ lookup('env','APP_NAME') }}"
    } 